const productos = [
  {
    id: 1,
    nombre: "SOL",
    zona: "CABALLITO",
    horario: "Lunes a sádados 9 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Masajista terapeutica. Masajes relajantes. Descontracturantes. Drenaje linfático. Masaje californiano.",
    telefono: "11 3303-8353",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541133038353&text=Hola%20SOL,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/sol/sol-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/sol/sol-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/sol/sol-punto-masajes-argentina-3-198x300.webp",
    img4: "./img/masajistas/sol/sol-punto-masajes-argentina-4-198x300.webp",
    destacada: true,
    posicion: 1,
    tag: "",
    activado: true,
  },
  {
    id: 2,
    nombre: "ESTRELLA",
    zona: "MICROCENTRO",
    horario: "Lunes a sádados 9 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes descontracturantes, relajantes, sensitivos desde los pies hasta la cervical. Servicio ducha. Lugar reservado y higiénico. Solo numeroS identificados, no atiendo llamadas.",
    telefono: "11 6900-5210",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541169005210&text=Hola%20ESTRELLA,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/estrella/estrella-punto-masajes-argentina-3-198x300.webp",
    img2: "./img/masajistas/estrella/estrella-punto-masajes-argentina-198x300.webp",
    img3: "./img/masajistas/estrella/estrella-punto-masajes-argentina-2-198x300.webp",
    img4: "./img/masajistas/estrella/estrella-punto-masajes-argentina-4-198x300.webp",
    destacada: true,
    posicion: 2,
    tag: "",
    activado: true,
  },
  {
    id: 3,
    nombre: "MONICA",
    zona: "PALERMO",
    horario: "Lunes a sádados 9 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes relajantes descontracturantes de los pies a la cervical. Las mejores técnicas de relajación para vos.",
    telefono: "11 4066-8679",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541140668679&text=Hola%MONICA,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/monica/monica-punto-masajes-argentina.webp",
    img2: "./img/masajistas/monica/monica-punto-masajes-argentina-198x300.webp",
    img3: "",
    img4: "",
    destacada: true,
    posicion: 3,
    tag: "",
    activado: true,
  },
  {
    id: 4,
    nombre: "LAURA",
    zona: "TRIBUNALES",
    horario: "Lunes a sábado 10 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes descontracturantes relajantes desde los pies hasta la cervical.",
    telefono: "11 6795-3440",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541167953440&text=Hola%20LAURA,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/laura/laura-punto-masajes-argentina-7-193x300.webp",
    img2: "./img/masajistas/laura/laura-punto-masajes-argentina-193x300.webp",
    img3: "./img/masajistas/laura/laura-punto-masajes-argentina-2-193x300.webp",
    img4: "./img/masajistas/laura/laura-punto-masajes-argentina-4-193x300.webp",
    destacada: true,
    posicion: 4,
    tag: "",
    activado: true,
  },
  {
    id: 5,
    nombre: "CANDE",
    zona: "PALERMO",
    horario: "Lunes a sábados de 14 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista profesional Sensitivo",
    descripcion:
      "Lo que te ofrezco es una sesión de masajes para descontracturar, tonificar y relajar, reflexología, circulación de sangre en piernas, los mismos son 100% reales. Me manejo con reserva de turnos. ",
    telefono: "11 2731-4346",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541127314346&text=Hola%20CANDE,%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/cande/cande-10-198x300.webp",
    img2: "./img/masajistas/cande/cande-6-198x300.webp",
    img3: "./img/masajistas/cande/cande-7-198x300.webp",
    img4: "./img/masajistas/cande/cande-8-198x300.webp",
    destacada: true,
    posicion: 5,
    tag: "",
    activado: true,
  },
  {
    id: 6,
    nombre: "JOHANA",
    zona: "BELGRANO",
    horario: "Full time",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes relajantes descontracturantes de los pies a la cervical.",
    telefono: "11 2770-6453",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541127706453&text=Hola%20JOHANA,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/johana/johana-punto-masajes-argentina-198x300.webp",
    img2: "",
    img3: "",
    img4: "",
    destacada: true,
    posicion: 6,
    tag: "",
    activado: true,
  },
  {
    id: 7,
    nombre: "ABRIL",
    zona: "PALERMO",
    horario: "Lunes a sábados de 14 a 20",
    pago: "Solo Efectivo",
    titular: "Masajista profesional",
    descripcion:
      "Masajes relajantes descontracturantes de los pies a la cervical.",
    telefono: "11 6242-1975",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541162421975&text=Hola%20ABRIL,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/abril/abril-punto-masajes-argentina.webp",
    img2: "./img/masajistas/abril/abril-punto-masajes-argentina-2.webp",
    img3: "./img/masajistas/abril/abril-punto-masajes-argentina-3.webp",
    img4: "./img/masajistas/abril/abril-punto-masajes-argentina-4.webp",
    destacada: true,
    posicion: 7,
    tag: "",
    activado: true,
  },
  {
    id: 8,
    nombre: "ROMINA",
    zona: "BARRIO NORTE",
    horario: "Lunes a sábados 11 a 21",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes relajantes descontracturantes de los pies a la cervical.",
    telefono: "11 4979-1654",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541149791654&text=Hola%20ROMINA,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/romina/romina-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/romina/romina-punto-masajes-argentina-2-198x300.webp",
    img3: "",
    img4: "",
    destacada: false,
    posicion: 8,
    tag: "",
    activado: true,
  },
  {
    id: 9,
    nombre: "MARIZA",
    zona: "BELGRANO",
    horario: "Lunes a sábados 12 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista matriculada",
    descripcion:
      "Masajes relajantes descontracturantes de los pies a la cervical.",
    telefono: "11 3235-3114",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541132353114&text=Hola%20MARIZA,%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/marisa/marisa-punto-masajes-argentina-4-198x300.webp",
    img2: "./img/masajistas/marisa/marisa-punto-masajes-argentina-198x300.webp",
    img3: "./img/masajistas/marisa/marisa-punto-masajes-argentina-2-198x300.webp",
    img4: "./img/masajistas/marisa/marisa-punto-masajes-argentina-3-198x300.webp",
    destacada: true,
    posicion: 9,
    tag: "",
    activado: true,
  },
  {
    id: 10,
    nombre: "ALE",
    zona: "BELGRANO",
    horario: "Lunes a sábados 13 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes relajantes descontracturantes de los pies a la cervical.",
    telefono: "11 4096-3004",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541140963004&text=Hola%20mALE,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/ale/alejandra-punto-masajes-argentina-1-198x300.webp",
    img2: "./img/masajistas/ale/alejandra-punto-masajes-argentina-2-1-198x300.webp",
    img3: "./img/masajistas/ale/alejandra-punto-masajes-argentina-3-1-198x300.webp",
    img4: "",
    destacada: false,
    posicion: 10,
    tag: "",
    activado: true,
  },
  {
    id: 11,
    nombre: "LUDMILA",
    zona: "MICROCENTRO",
    horario: "Lunes a viernes 11 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista profesional",
    descripcion:
      "Soy masajista profesional matriculada n6921. TECNICA PROPIA.. realizo masajes descontracturantes relajantes, sedativos, deportivos, antiestres, aromaterapia, tailandes.",
    telefono: "11 6154-6886",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541161546886&text=Hola%20LUDMILA,%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/ludmila/ludmila-punto-masajes-argentina-3-198x300.webp",
    img2: "./img/masajistas/ludmila/ludmila-punto-masajes-argentina-2-1-198x300.webp",
    img3: "./img/masajistas/ludmila/ludmila-punto-masajes-argentina-4-198x300.webp",
    img4: "",
    destacada: true,
    posicion: 11,
    tag: "",
    activado: true,
  },
  {
    id: 12,
    nombre: "ELIANA",
    zona: "VILLA CRESPO",
    horario: "Lunes a sábados 9 a 16",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes relajantes, descontracturantes de pies hasta la cervical. Tambien hago domicilios.",
    telefono: "11 2586-1528",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541125861528&text=Hola%20ELIANA,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/eliana/eliana-punto-masajes-argentina-3-198x300.webp",
    img2: "./img/masajistas/eliana/eliana-punto-masajes-argentina-198x300.webp",
    img3: "./img/masajistas/eliana/eliana-punto-masajes-argentina-2-198x300.webp",
    img4: "",
    destacada: false,
    posicion: 12,
    tag: "",
    activado: true,
  },
  {
    id: 13,
    nombre: "GABRIELA",
    zona: "COLEGIALES",
    horario: "Lunes a sábados 13 a 21",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista profesional",
    descripcion:
      "Trabajo sobre camilla y tatami. Depilacion sistema español Consultorio propio.",
    telefono: "11 3048-1072",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541130481072&text=Hola%20GABRIELA,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/gabriela/gabriela-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/gabriela/gabriela-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/gabriela/gabriela-punto-masajes-argentina-3-198x300.webp",
    img4: "",
    destacada: false,
    posicion: 13,
    tag: "",
    activado: true,
  },
  {
    id: 14,
    nombre: "KALU",
    zona: "PALERMO",
    horario: "Lunes a viernes 9 a 22 / sábados y domingos con turnos",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista profesional",
    descripcion:
      "Masajes relajantes descontracturantes de los pies a la cervical.",
    telefono: "11 2711-6874",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541127116874&text=Hola%20KALU,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/kalu/tete-punto-masajes-argentina-3-198x300.webp",
    img2: "./img/masajistas/kalu/tete-punto-masajes-argentina-198x300.webp",
    img3: "./img/masajistas/kalu/tete-punto-masajes-argentina-2-198x300.webp",
    img4: "",
    destacada: false,
    posicion: 14,
    tag: "",
    activado: true,
  },
  {
    id: 15,
    nombre: "BARBIE",
    zona: "PALERMO",
    horario: "Full time",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes relajantes descontracturantes de los pies a la cervical.",
    telefono: "11 3158-9844",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541131589844&text=Hola%20BARBIE,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/barbie/barbie-punto-masajes-argentina-198x300.webp",
    img2: "",
    img3: "",
    img4: "",
    destacada: true,
    posicion: 15,
    tag: "",
    activado: true,
  },
  {
    id: 16,
    nombre: "ROSITA",
    zona: "PALERMO",
    horario: "Lunes a viernes 10 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes relajantes descontracturantes de los pies a la cervical.",
    telefono: "11 3386-9889",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541133869889&text=Hola%20ROSITA,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/rosita/rosita-punto-masajes-argentina-2.webp",
    img2: "./img/masajistas/rosita/rosita-punto-masajes-argentina.webp",
    img3: "",
    img4: "",
    destacada: true,
    posicion: 16,
    tag: "",
    activado: true,
  },
  {
    id: 17,
    nombre: "RAQUEL",
    zona: "VILLA CRESPO",
    horario: "Lunes a sábados 10 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Diferentes técnicas de masajes relajante, descontracturante, linfatico, piedras calientes sobre camilla. Música ambiental. Servicio de ducha. Soy independiente. Me manejo con reserva de turnos.",
    telefono: "11 2641-0445",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541126410445&text=Hola%20RAQUEL,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/raquel/raquel-punto-masajes-argentina-3-198x300.webp",
    img2: "./img/masajistas/raquel/raquel-punto-masajes-argentina-198x300.webp",
    img3: "./img/masajistas/raquel/raquel-punto-masajes-argentina-2-198x300.webp",
    img4: "./img/masajistas/raquel/raquel-punto-masajes-argentina-5-198x300.webp",
    destacada: true,
    posicion: 17,
    tag: "",
    activado: true,
  },
  {
    id: 18,
    nombre: "VIOLETA",
    zona: "TRIBUNALES",
    horario: "Lunes a sábados 10 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes sensitivos",
    descripcion:
      "Soy masajista matriculada… y brindo excelentes masajes sobre camilla o tatami. Descontracturantes, deportivos, sensitivos.",
    telefono: "11 6487-0037",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541164870037&text=Hola%20NOEMI,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/violeta/violeta-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/violeta/violeta-punto-masajes-argentina-2-198x300.webp",
    img3: "",
    img4: "",
    destacada: false,
    posicion: 18,
    tag: "",
    activado: true,
  },
  {
    id: 19,
    nombre: "ALISON",
    zona: "PALERMO",
    horario: "Lunes a sábados de 10 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Te Ofrezco Un Servicio De Masaje Descontraturante Sedactivo Y Relajante En Todo Tu Cuerpo Veni A Disfrutar De Un Momento Único En Un Ambiente Totalmente Climatizado. Con Servicio De Ducha.",
    telefono: "11 3695-4892",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541136954892&text=Hola%20ALISON,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/alison/alison-punto-masajes-argentina-4.webp",
    img2: "./img/masajistas/alison/alison-punto-masajes-argentina.webp",
    img3: "./img/masajistas/alison/alison-punto-masajes-argentina-2.webp",
    img4: "./img/masajistas/alison/alison-punto-masajes-argentina-3.webp",
    destacada: true,
    posicion: 19,
    tag: "",
    activado: true,
  },
  {
    id: 20,
    nombre: "LARA",
    zona: "TRIBUNALES",
    horario: "Lunes, domingos y feriados 10 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Realizo masajes descontracturantes, relajantes , sedativos , deportivos, reflexologia de manos y pies. Ambiente climatizado y kit de ducha. Atención ambos sexos.",
    telefono: "11 5143-6642",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541151436642&text=Hola%20LARA,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/lara/lara-punto-masajes-argentina.webp",
    img2: "./img/masajistas/lara/lara-punto-masajes-argentina-2.webp",
    img3: "./img/masajistas/lara/lara-punto-masajes-argentina-3.webp",
    img4: "./img/masajistas/lara/lara-punto-masajes-argentina-4.webp",
    destacada: true,
    posicion: 20,
    tag: "",
    activado: true,
  },
  {
    id: 21,
    nombre: "MARIAN",
    zona: "MICROCENTRO",
    horario: "Lunes a viernes de 10 a 20 y sábados de 11 a 18",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista matriculada",
    descripcion:
      "Realizo masajes Profesionales Descontraturantes, anti stress, Deportivo, relajantes, sensitivo, drenaje linfático, Reflexología. Depilación tratamientos estéticos con aparatologías de vanguardia.",
    telefono: "11 2500-0455",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541125000455&text=Hola%20MARIAN,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/marian/marian-punto-masajes-argentina-3-198x300.webp",
    img2: "./img/masajistas/marian/marian-punto-masajes-argentina-198x300.webp",
    img3: "./img/masajistas/marian/marian-punto-masajes-argentina-2-198x300.webp",
    img4: "./img/masajistas/marian/marian-punto-masajes-argentina-4-198x300.webp",
    destacada: true,
    posicion: 21,
    tag: "",
    activado: true,
  },
  {
    id: 22,
    nombre: "BRIANA",
    zona: "RECOLETA",
    horario: "Lunes a domingos 10 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes relajantes descontracturantes de los pies a la cervical.",
    telefono: "11 3145-4965",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541131454965&text=Hola%20BRIANA,%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/briana/briana-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/briana/briana-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/briana/briana-punto-masajes-argentina-3-198x300.webp",
    img4: "./img/masajistas/briana/briana-punto-masajes-argentina-4-198x300.webp",
    destacada: true,
    posicion: 22,
    tag: "",
    activado: true,
  },
  {
    id: 23,
    nombre: "PATRICIA",
    zona: "TRIBUNALES",
    horario: "Lunes a sábados de 11 a 19",
    pago: "Solo Efectivo",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes relajantes descontracturantes de los pies a la cervical.",
    telefono: "11 2733-8975",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541127338975&text=Hola%20PATRICIA,%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/patricia/patricia-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/patricia/patricia-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/patricia/patricia-punto-masajes-argentina-3-198x300.webp",
    img4: "",
    destacada: true,
    posicion: 23,
    tag: "",
    activado: true,
  },
  {
    id: 24,
    nombre: "SOFIA",
    zona: "MICROCENTRO",
    horario: "Lunes a sábado 11 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes sensitivos",
    descripcion:
      "Masajes relajantes descontracturantes de los pies a la cervical.",
    telefono: "11 6217-7502",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541162177502&text=Hola%20SOFIA,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/sofia/punto-masajes-sofia-2-198x300.webp",
    img2: "./img/masajistas/sofia/punto-masajes-sofia-198x300.webp",
    img3: "./img/masajistas/sofia/punto-masajes-sofia-3-198x300.webp",
    img4: "",
    destacada: false,
    posicion: 24,
    tag: "",
    activado: false,
  },
  {
    id: 25,
    nombre: "PAULA",
    zona: "GARIN",
    horario: "Lunes a viernes 11 a 18",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes profesionales",
    descripcion:
      "Masajista terapéutica especializada en tratamiento del dolor muscular. Masajes anti stress y drenaje linfático. Consultorio personal en zona céntrica de Garín, libre estacionamiento. ",
    telefono: "11 3477-7793",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541134777793&text=Hola%20PAULA,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/paula/ana-laura-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/paula/ana-laura-punto-masajes-argentina-2-198x300.webp",
    img3: "",
    img4: "",
    destacada: false,
    posicion: 25,
    tag: "",
    activado: true,
  },
  {
    id: 26,
    nombre: "VERO",
    zona: "MICROCENTRO",
    horario: "Lunes a sábado 10 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista Profesional",
    descripcion:
      "Masajes integral de cuerpo entero con varias técnicas en un ambiente tranquilo , climatizado muy moderno y cómodo. Trabajo sobre camilla o Tatami.Servicio de ducha. Privacidad absoluta.",
    telefono: "11 4477-8606",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541144778606&text=Hola%20VERO%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/vero/vero-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/vero/vero-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/vero/vero-punto-masajes-argentina-3-198x300.webp",
    img4: "./img/masajistas/vero/vero-punto-masajes-argentina-4-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },

  {
    id: 27,
    nombre: "DAIANA",
    zona: "CONGRESO",
    horario: "Lunes a viernes 11 a 17",
    pago: "Solo Efectivo",
    titular: "Masoterapeuta Matriculada",
    descripcion:
      "Masajes profesionales, descontracturante, relajante y Antiestrés para aliviar tensión muscular y dolencia por malas posturas. Ambiente cómodo y climatizado. Servicio de ducha disponible.",
    telefono: "11 2833-6272",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541128336272&text=Hola%20DAIANA%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/daiana/daiana-punto-masajes-argentina-2.webp",
    img2: "./img/masajistas/daiana/daiana-punto-masajes-argentina-1-198x300.webp",
    img3: "./img/masajistas/daiana/daiana-punto-masajes-argentina-2-1-198x300.webp",
    img4: "./img/masajistas/daiana/daiana-punto-masajes-argentina.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 28,
    nombre: "MARIELA",
    zona: "MICROCENTRO",
    horario: "Lunes a domingos 10 a 21",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes sensitivos",
    descripcion:
      "Masajes sensuales, sensitivos, descontracturantes, relajantes desde los pies hasta la cervical.",
    telefono: "11 4946-1581",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541149461581&text=Hola%20MARIELA,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/mariela/mariela-punto-masajes-argentina.webp",
    img2: "./img/masajistas/mariela/mariela-punto-masajes-argentina-198x300.webp",
    img3: "./img/masajistas/mariela/mariela-punto-masajes-argentina-3-198x300.webp",
    img4: "./img/masajistas/mariela/mariela-punto-masajes-argentina-4-198x300.webp",
    destacada: true,
    posicion: "",
    tag: "pago",
    activado: true,
  },
  {
    id: 29,
    nombre: "YANINA",
    zona: "MICROCENTRO",
    horario: "Lunes a sábados 12 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes sensitivos",
    descripcion:
      "Masajes en tatami y camilla relajante muscular sensitivo descontracturantes servicio de ducha efectivo y mp.",
    telefono: "11 3367-9535",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541133679535&text=Hola%20YANINA,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/yanina/yanina-punto-masajes-argentina--198x300.webp",
    img2: "./img/masajistas/yanina/yanina-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/yanina/yanina-punto-masajes-argentina-4-198x300.webp",
    img4: "./img/masajistas/yanina/yanina-punto-masajes-argentina-6-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 30,
    nombre: "YANA",
    zona: "MICROCENTRO",
    horario: "Lunes a viernes 11 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista",
    descripcion: "Masajes descontracturantes deportivos sedativos.",
    telefono: "11 6837-7676",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541168377676&text=Hola%20YANA,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/yana/daniela-punto-masajes-198x300.webp",
    img2: "./img/masajistas/yana/daniela-punto-masajes-2-198x300.webp",
    img3: "",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 31,
    nombre: "AGUSTINA",
    zona: "CABALLITO",
    horario: "Lunes a sábados 11 a 18",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes sensitivos",
    descripcion:
      "Soy masajista matriculada y te ofrezco una sesión de masajes de pies a cervical relajantes descontracturante sobre camilla o tatami. Cuento con servicio de ducha ambiente climatizado.",
    telefono: "11 4980-9485",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541149809485&text=Hola%20AGUS,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/agus/agus-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/agus/agus-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/agus/agus-punto-masajes-argentina-3-198x300.webp",
    img4: "./img/masajistas/agus/agus-punto-masajes-argentina-4-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 32,
    nombre: "FLORENCIA",
    zona: "BELGRANO",
    horario: "Lunes a viernes 8:30 a 21",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes californianos",
    descripcion:
      "Masajes en todo el cuerpo caracterizado por movimientos largos y fluidos que te permiten relajarte, tomar conciencia corporal. Ademas trabajo para contracturas y bloqueos. ",
    telefono: "11 2465-3691",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541124653691&text=Hola%20FLORENCIA,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/florencia/florencia-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/florencia/florencia-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/florencia/florencia-punto-masajes-argentina-3-198x300.webp",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 33,
    nombre: "EMMA",
    zona: "BELGRANO",
    horario: "Lunes a sábados 10 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes relajantes descontracturantes sedativos de los pies a la cabeza.",
    telefono: "11 7607-3209",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541176073209&text=Hola%20EMMA,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/emma/emma-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/emma/emma-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/emma/emma-punto-masajes-argentina-3-198x300.webp",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 34,
    nombre: "MARIELA",
    zona: "PALERMO",
    horario: "Lunes a viernes 11 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Te ofrezco masajes descontracturantes, sedativos, sensitivos, anti estrés, sobre camilla profesional. Cuento con servicio de ducha, ambiente discreto y climatizado. ",
    telefono: "11 6826-2683",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541168262683&text=Hola%20PALERMO,%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/mariela-2/mariela-punto-masajes-argentina-2-1-198x300.webp",
    img2: "",
    img3: "",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 35,
    nombre: "ROSA",
    zona: "ITUZAINGO",
    horario: "Lunes a viernes 10 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista Profesional",
    descripcion:
      "Masoterapeuta profesional realizo: Masajes relajantes, descontracturantes, masajes reductores, de pies a cabeza o focalizado. Contamos con ambiente climatizado y servicio de ducha.",
    telefono: "11 5846-2883",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541158462883&text=Hola%20ROSA,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/rosa/rosa-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/rosa/rosa-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/rosa/rosa-punto-masajes-argentina-3-198x300.webp",
    img4: "./img/masajistas/rosa/rosa-punto-masajes-argentina-4-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 36,
    nombre: "NATHALY",
    zona: "CABALLITO",
    horario: "Lunes a sábados 12 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista venezolana",
    descripcion:
      "Realizo masajes relajantes, descontracturantes, deportivos y sedativos. Con reserva previa de turnos.",
    telefono: "11 6378-3915",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541163783915&text=Hola%20NATHALY,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/nathaly/nathaly-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/nathaly/nathaly-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/nathaly/nathaly-punto-masajes-argentina-3-198x300.webp",
    img4: "./img/masajistas/nathaly/nathaly-punto-masajes-argentina-4-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: false,
  },
  {
    id: 37,
    nombre: "MICAELA",
    zona: "VILLA DEVOTO",
    horario: "Lunes a sábados 11 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista profesional",
    descripcion:
      "Masajes relajantes, descontracturantes, sedativos y deportivos, de pies a cabeza. Podés ducharte de acuerdo a tu preferencia. Velas. Música. Aromas. Ambiente confortable.",
    telefono: "11 7132-4074",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541171324074&text=Hola%20SOLEDAD,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/micaela/micaela-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/micaela/micaela-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/micaela/micaela-punto-masajes-argentina-3-198x300.webp",
    img4: "./img/masajistas/micaela/micaela-punto-masajes-argentina-4-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 38,
    nombre: "SOLEDAD",
    zona: "PATERNAL",
    horario: "Lunes a viernes 11 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista profesional",
    descripcion:
      "Masajes reales, fuertes o suaves, de pies a cervical. Descontracturantes. Circulatorios. Relajantes. Sensitivos. Trabajo sobre camastro de spa. Servicio de ducha. Ambiente climatizado.",
    telefono: "11 5794-2067",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541157942067&text=Hola%20SOLEDAD,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/soledad/soledad-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/soledad/soledad-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/soledad/soledad-punto-masajes-argentina-3-198x300.webp",
    img4: "./img/masajistas/soledad/soledad-punto-masajes-argentina-4-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 39,
    nombre: "BELEN",
    zona: "BELGRANO",
    horario: "Lunes a sábados 13 a 20:30",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista profesional",
    descripcion:
      "Masajes relajantes sedativos descontracturantes de los pies a la cervical.",
    telefono: "11 3072-4010",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541130724010&text=Hola%20BELEN,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/belen/belen-punto-masajes-argentina-1-198x300.webp",
    img2: "./img/masajistas/belen/belen-punto-masajes-argentina-2-1-198x300.webp",
    img3: "",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 40,
    nombre: "LARA",
    zona: "CABALLITO",
    horario: "Lunes a sábados 11 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes relajantes sedativos descontracturantes de los pies a la cervical.",
    telefono: "11 4157-4154",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541141574154&text=Hola%20mLARA,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/lara-2/lara-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/lara-2/lara-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/lara-2/lara-punto-masajes-argentina-3-198x300.webp",
    img4: "./img/masajistas/lara-2/lara-punto-masajes-argentina-4-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 41,
    nombre: "FERNANDA",
    zona: "RECOLETA",
    horario: "Lunes a domingos 8 a 22",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Realizo masajes, estiramientos y elongación muscular. La sesión dura una hora y lo realizó sobre tatami. Para tu comodidad tenes servicio de ducha antes y después del masaje.",
    telefono: "11 2294-3358",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541122943358&text=Hola%20FERNANDA,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/fernanda/fernanda-punto-masajes-argentina-1-198x300.webp",
    img2: "./img/masajistas/fernanda/fernanda-punto-masajes-argentina-2-1-198x300.webp",
    img3: "./img/masajistas/fernanda/fernanda-punto-masajes-argentina-3-1-198x300.webp",
    img4: "./img/masajistas/fernanda/fernanda-punto-masajes-argentina-4-1-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 42,
    nombre: "NAHIR",
    zona: "BELGRANO",
    horario: "Lunes a sábados 11 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Realizo masajes, estiramientos y elongación muscular. La sesión dura una hora y lo realizó sobre tatami. Para tu comodidad tenes servicio de ducha antes y después del masaje.",
    telefono: "11 3903-1445",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541139031445&text=Hola%20NAHIR,%20te%20vi%20en%20Punto%20Masajes.%20Contame%20de%20tu%20servicio.",
    img: "./img/masajistas/nahir/nahir-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/nahir/nahir-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/nahir/nahir-punto-masajes-argentina-3-198x300.webp",
    img4: "./img/masajistas/nahir/nahir-punto-masajes-argentina-4-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 43,
    nombre: "DANIELA",
    zona: "PALERMO",
    horario: "Lunes a sábados 10 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista profesional",
    descripcion:
      "Masajes relajantes descontracturantes sedativos sensitivos reflexología …Masajes integrales de los pies a la cabeza.",
    telefono: "11 4477-5106",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541144775106&text=Hola%20DANIELA,%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/daniela/daniela-punto-masajes-argentina.webp",
    img2: "./img/masajistas/daniela/daniela-punto-masajes-argentina-2.webp",
    img3: "./img/masajistas/daniela/daniela-punto-masajes-argentina-3.webp",
    img4: "./img/masajistas/daniela/daniela-punto-masajes-argentina-4.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 44,
    nombre: "MARIA",
    zona: "CONGRESO",
    horario: "Lunes a domingos 12 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes relajantes y descontracturantes en todo el cuerpo con reserva previa de turnos.",
    telefono: "11 5403-4669",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541154034669&text=Hola%20MARIA,%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/maria/maria-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/maria/maria-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/maria/maria-punto-masajes-argentina-3-198x300.webp",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 45,
    nombre: "LAURA",
    zona: "BELGRANO",
    horario: "Lunes a viernes 9 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes descontracturantes",
    descripcion:
      "Masajes descontracturantes, relajantes y sedativos. Mi lugar es ideal, tranquilo y reservado. Utilizo música ambiental. Ambiente climatizado. Servicio de ducha, antes y después de la sesión.",
    telefono: "11 6137-2821",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541161372821&text=Hola%20LAURA,%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/laura-2/laura-punto-masajes-argentina-1-198x300.webp",
    img2: "./img/masajistas/laura-2/laura-punto-masajes-argentina-2-1-198x300.webp",
    img3: "./img/masajistas/laura-2/laura-punto-masajes-argentina-3-198x300.webp",
    img4: "./img/masajistas/laura-2/laura-punto-masajes-argentina-3-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: false,
  },
  {
    id: 46,
    nombre: "IVANNA",
    zona: "CABALLITO",
    horario: "Lunes a sábados 10 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes terapéuticos",
    descripcion:
      "Utilizo diferentes técnicas. Sobre camilla o tatami. Ambiente climatizado. Buena atención. Con reserva de turnos.",
    telefono: "11 3820-8469",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541138208469&text=Hola%20IVANNA,%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/ivanna/ivanna-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/ivanna/ivanna-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/ivanna/ivanna-punto-masajes-argentina-3-198x300.webp",
    img4: "./img/masajistas/ivanna/ivanna-punto-masajes-argentina-4-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 47,
    nombre: "CARMEN",
    zona: "MICROCENTRO",
    horario: "Lunes a domingos 8 a 21",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista profesional",
    descripcion:
      "Masaje Californiano. Relajante. Sedativo. Sensitivo. Sobre camilla. Con reserva anticipada de turnos.",
    telefono: "11 4429-0093",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541144290093&text=Hola%20CARMEN,%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/carmen/carmen-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/carmen/carmen-punto-masajes-argentina-2-198x300.webp",
    img3: "",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 48,
    nombre: "VIRGINIA",
    zona: "MICROCENTRO",
    horario: "Lunes a sábados 12 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista profesional",
    descripcion:
      "Masajes sedativos, relajantes, descontracturantes y deportivos. Estiramientos corporales posturales. Anti estrés de pies a cervical.",
    telefono: "11 2608-6936",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541126086936&text=Hola%20VIRGINIA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/virginia/virginia-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/virginia/virginia-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/virginia/virginia-punto-masajes-argentina-3-198x300.webp",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 49,
    nombre: "ANGELA",
    zona: "MUNRO",
    horario: "Lunes a sábados 10 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista Matriculada",
    descripcion:
      "Masajes terapéuticos, descontracturantes, relajantes y sedativos. Manicuría. Pedicuría. Depilación.",
    telefono: "11 6846-9689",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541168469689&text=Hola%20ANGELA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/angela/angela-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/angela/angela-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/angela/angela-punto-masajes-argentina-3-198x300.webp",
    img4: "./img/masajistas/angela/angela-punto-masajes-argentina-4-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 50,
    nombre: "LESLIE",
    zona: "BELGRANO",
    horario: "Lunes a sábados 8 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista Profesional",
    descripcion:
      "Realizo masajes relajantes, descontracturantes y sedativos. Trabajo en camilla y tatami. Ambiente climatizado. Con reserva previa de turnos.",
    telefono: "11 5178-8475",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541151788475&text=Hola%20LESLIE%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/leslie/leslie-punto-masajes-argentina-1-198x300.webp",
    img2: "./img/masajistas/leslie/leslie-punto-masajes-argentina-3-198x300.webp",
    img3: "./img/masajistas/leslie/leslie-punto-masajes-argentina-4-198x300.webp",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 51,
    nombre: "KARELYS",
    zona: "CABALLITO",
    horario: "Lunes a domingos 8 a 21",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes para el alma",
    descripcion:
      "Encontremos los momentos para los mejores masajes descontracturantes, relajantes, utilizando todas las técnicas. Cuento con excelente ambientación.",
    telefono: "11 5727-7434",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541157277434&text=Hola%20KARELYS%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/karelys/karelys-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/karelys/karelys-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/karelys/karelys-punto-masajes-argentina-3-198x300.webp",
    img4: "./img/masajistas/karelys/karelys-punto-masajes-argentina-4-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 52,
    nombre: "MONICA",
    zona: "MONTSERRAT",
    horario: "Lunes a viernes 10 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masoterapeuta profesional",
    descripcion:
      "Trabajo sobre camilla. Ambiente climatizado. Utilizo diferentes técnicas de masajes en todo el cuerpo: deportivos, sensitivos, sedativos, relajantes y descontracturantes.",
    telefono: "11 3926-4543",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541139264543&text=Hola%20MONICA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/monica-2/monica-punto-masajes-argentina-1-198x300.webp",
    img2: "./img/masajistas/monica-2/monica-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/monica-2/monica-punto-masajes-argentina-3-198x300.webp",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 53,
    nombre: "ALICIA",
    zona: "MICROCENTRO",
    horario: "Lunes a viernes 11 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista profesional",
    descripcion:
      "Masajes antiestrés, descontracturantes, sedativos, circulatorios y deportivos. Drenaje linfático manual.  Lámpara. Estética. Cosmetología. Manicuría. Pedicuría. Depilación Masculina.",
    telefono: "11 2237-0406",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541122370406&text=Hola%20ALICIA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/alicia/alicia-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/alicia/alicia-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/alicia/alicia-punto-masajes-argentina-3-198x300.webp",
    img4: "./img/masajistas/alicia/alicia-punto-masajes-argentina-4-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 54,
    nombre: "DANIELA",
    zona: "BELGRANO",
    horario: "Lunes a sábados 12 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Atención en spa de primer nivel. Masajes relajantes y descontracturantes.",
    telefono: "11 2863-1226",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541128631226&text=Hola%20DANIELA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/daniela-2/daniela-punto-masajes-argentina-2-4-198x300.webp",
    img2: "./img/masajistas/daniela-2/daniela-punto-masajes-argentina-7-198x300.webp",
    img3: "",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 55,
    nombre: "CAROLINA",
    zona: "BELGRANO",
    horario: "Lunes a viernes 10 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes descontracturantes",
    descripcion:
      "Masajes descontracturantes, relajantes, sensitivos y sedativos. Trabajo sobre camilla o tatami. Con reserva de turnos.",
    telefono: "11 2601-1930",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541126011930&text=Hola%20CAROLINA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/carolina/carolina-punto-masajes-argentina-2-2-198x300.webp",
    img2: "./img/masajistas/carolina/carolina-punto-masajes-argentina-3-2-198x300.webp",
    img3: "./img/masajistas/carolina/carolina-punto-masajes-argentina-4-1-198x300.webp",
    img4: "./img/masajistas/carolina/carolina-punto-masajes-argentina-5-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 56,
    nombre: "MARIEL",
    zona: "CABALLITO",
    horario: "Lunes a domingos 11 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista Profesional",
    descripcion:
      "Masajes descontracturantes, relajantes y sensitivos, sobre camilla profesional o tatami japonés. Ambiente climatizado y música funcional. Servicio de baño.",
    telefono: "11 6877-3522",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541168773522&text=Hola%20MARIEL%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/mariel/mariel-2-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/mariel/mariel-punto-masajes-argentina-198x300.webp",
    img3: "./img/masajistas/mariel/mariel-punto-masajes-argentina-198x300.webp",
    img4: "./img/masajistas/mariel/mariel-punto-masajes-argentina-3-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 57,
    nombre: "JENIFER",
    zona: "CABALLITO",
    horario: "Lunes a sábados 11 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista Profesional",
    descripcion:
      "Realizo masajes terapéuticos con distintas técnicas. Limpieza facial profunda con microdermoabrasión. Fototerapia. Piedras calientes. Ambiente climatizado.",
    telefono: "11 2620-6385",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541126206385&text=Hola%20JENNIFER%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/jennifer/jennifer-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/jennifer/jennifer-punto-masajes-argentina-3-1-198x300.webp",
    img3: "./img/masajistas/jennifer/jennifer-punto-masajes-argentina-3-198x300.webp",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 58,
    nombre: "PAOLA",
    zona: "VILLA LURO",
    horario: "Lunes a domingos 10 a 21",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes terapeuticos",
    descripcion:
      "Utilizo diferentes técnicas. Ambiente tranquilo con música relajante. Trabajo sobre camilla o tatami. Buena atención. Servicio de ducha. Con reserva de turnos.",
    telefono: "11 3194-7208",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541131947208&text=Hola%20PAOLA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/paola/paola-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/paola/paola-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/paola/paola-punto-masajes-argentina-3-198x300.webp",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 59,
    nombre: "VERONICA",
    zona: "MARTINEZ",
    horario: "Martes a viernes 13 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes terapeuticos",
    descripcion:
      "Te ofrezco una sesión de masajes relajantes y descontracturantes, sobre camilla o tatami. Utilizo cremas y aceites de calidad. Ambiente muy agradable y climatizado. Servicio de ducha.",
    telefono: "11 3849-4947",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541138494947&text=Hola%20VERONICA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/veronica/veronica-punto-masajes-argentina-2-198x300.webp",
    img2: "./img/masajistas/veronica/veronica-punto-masajes-argentina-3-198x300.webp",
    img3: "./img/masajistas/veronica/veronica-punto-masajes-argentina-4-198x300.webp",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 60,
    nombre: "LUISA",
    zona: "MUNRO",
    horario: "Lunes a sábados 10 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista Matriculada",
    descripcion:
      "Masaje terapéutico. Descontracturante. Deportivo. Drenaje linfático. Circulatorio. Sedativo. Relajante. Belleza de manos y pies.",
    telefono: "11 5178-5954",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541151785954&text=Hola%20LUISA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/luisa/luisa-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/luisa/luisa-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/luisa/luisa-punto-masajes-argentina-3-198x300.webp",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 61,
    nombre: "FLAVIA",
    zona: "TRIBUNALES",
    horario: "Lunes a viernes 13 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista Matriculada",
    descripcion:
      "Masajes totalmente profesionales, sobre camilla o tatami. Relajantes. Descontracturantes. Deportivos. Shiatsu. Piedras calientes. Reflexología. Ambiente climatizado.",
    telefono: "11 5568-8034",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541155688034&text=Hola%20FLAVIA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/flavia/flavia-punto-masajes-argentina-2-198x300.webp",
    img2: "./img/masajistas/flavia/flavia-punto-masajes-argentina-3-198x300.webp",
    img3: "./img/masajistas/flavia/flavia-punto-masajes-argentina-3-198x300.webp",
    img4: "./img/masajistas/flavia/flavia-punto-masajes-argentina-4-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 62,
    nombre: "EUGENIA",
    zona: "CONGRESO",
    horario: "Lunes a sábados 11 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes profesionales",
    descripcion:
      "Masajes descontracturantes, sedativos y relajantes, de pies a cervical, cuerpo completo. Servicio de ducha. Ambiente climatizado.",
    telefono: "11 2580-6165",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541125806165&text=Hola%20EUGENIA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/eugenia/eugenia-punto-masajes-argentina-198x300.webp",
    img2: "./img/masajistas/eugenia/eugenia-punto-masajes-argentina-2-198x300.webp",
    img3: "./img/masajistas/eugenia/eugenia-punto-masajes-argentina-3-198x300.webp",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 63,
    nombre: "MARIELA",
    zona: "VILLA CRESPO",
    horario: "Lunes a viernes 11 a 21",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes profesionales",
    descripcion:
      "Masajes descontracturantes, relajantes, antiestrés, energizantes y sedativos. Sobre camilla profesional. Ambiente climatizado.",
    telefono: "11 5574-2574",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541155742574&text=Hola%20MARIELA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/mariela-3/mariela-punto-masajes-argentina-7-198x300.webp",
    img2: "",
    img3: "",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: false,
  },
  {
    id: 64,
    nombre: "MARIA",
    zona: "TRIBUNALES",
    horario: "Lunes a viernes 10 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista profesional",
    descripcion:
      "Masajes relajantes y descontracturantes. Con reserva previa de turnos.",
    telefono: "11 6947-5764",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541169475764&text=Hola%20MARIA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/maria-2/maria-punto-masajes-argentina-3-2-198x300.webp",
    img2: "./img/masajistas/maria-2/maria-punto-masajes-argentina-2-2-198x300.webp",
    img3: "./img/masajistas/maria-2/maria-punto-masajes-argentina-4-198x300.webp",
    img4: "./img/masajistas/maria-2/maria-punto-masajes-argentina-5-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 65,
    nombre: "MARIA",
    zona: "TRIBUNALES",
    horario: "Lunes a sábados 9 a 21",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista profesional",
    descripcion:
      "Masajes descontracturantes, deportivos y sedativos. En un ambiente confortable con música relajante, servicio de ducha y calefacción.",
    telefono: "11 6727-9483",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541167279483&text=Hola%20MARIA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/maria-3/maria-punto-masajes-argentina-2-3-198x300.webp",
    img2: "./img/masajistas/maria-3/maria-punto-masajes-argentina-3-3-198x300.webp",
    img3: "./img/masajistas/maria-3/maria-punto-masajes-argentina-4-1-198x300.webp",
    img4: "./img/masajistas/maria-3/maria-punto-masajes-argentina-6-198x300.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 66,
    nombre: "ROMINA",
    zona: "BALLESTER",
    horario: "Lunes a viernes 9 a 19",
    pago: "Solo Efectivo",
    titular: "Masajista profesional",
    descripcion:
      "Masajes descontracturantes relajantes y sedativos, tratamientos segun tu dolencia.",
    telefono: "11 6135-5206",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541161355206&text=Hola%20ROMINA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/romina-2/romina-punto-masajes-argentina.webp",
    img2: "./img/masajistas/romina-2/romina-punto-masajes-argentina-3.webp",
    img3: "./img/masajistas/romina-2/romina-punto-masajes-argentina-2.webp",
    img4: "./img/masajistas/romina-2/romina-punto-masajes-argentina-4.webp.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 67,
    nombre: "ARIANA",
    zona: "TRIBUNALES",
    horario: "Lunes a sábados 10 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes Terapéuticos",
    descripcion:
      "Soy masajista matriculada. Te brindo masajes terapéuticos, descontracturantes, relajantes y deportivos. Masaje Integral. Atiendo en mi consultorio, total privacidad. Reservá tu turno.",
    telefono: "11 4057-8235",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541140578235&text=Hola%20ARIANA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/ariana/ariana-punto-masajes-argentina.webp",
    img2: "./img/masajistas/ariana/ariana-punto-masajes-argentina-2.webp",
    img3: "./img/masajistas/ariana/ariana-punto-masajes-argentina-3.webp",
    img4: "./img/masajistas/ariana/ariana-punto-masajes-argentina-4.webp",
    destacada: true,
    posicion: "",
    tag: "pago",
    activado: true,
  },
  {
    id: 68,
    nombre: "FRANCISMAR",
    zona: "CONGRESO",
    horario: "Lunes a sábados 11:30 a 20",
    pago: "Solo Efectivo",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes super lindos relajantes, sedativos o relajantes de pies a cervical.",
    telefono: "11 6573-0173",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541165730173&text=Hola%20FRANCISMAR%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/francismar/francismar-punto-masajes-argentina-2.webp",
    img2: "./img/masajistas/francismar/francismar-punto-masajes-argentina-3.webp",
    img3: "./img/masajistas/francismar/francismar-punto-masajes-argentina-4.webp",
    img4: "./img/masajistas/francismar/francismar-punto-masajes-argentina.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 69,
    nombre: "LIZ",
    zona: "MONTSERRAT",
    horario: "Lunes a sábados 13 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes reales",
    descripcion:
      "Mis masajes son descontracturantes, relajantes y sensitivos, cuerpo completo, sobre camilla 1 hora o media hora.",
    telefono: "11 6627-1773",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541166271773&text=Hola%20LIZ%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/liz/liz-punto-masajes-argentina.webp",
    img2: "./img/masajistas/liz/liz-punto-masajes-argentina-2.webp",
    img3: "./img/masajistas/liz/liz-punto-masajes-argentina-3.webp",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 70,
    nombre: "CAMI",
    zona: "TRIBUNALES",
    horario: "Lunes a domingos 11 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista",
    descripcion:
      "Realizo sobre camilla o tatami japonés. Son masajes relajantes, descontracturantes, sedativos ambos lados de el cuerpo, me manejo con reserva de turno.",
    telefono: "11 2519-5514",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541125195514&text=Hola%20CAMI%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/cami/cami-punto-masajes-argentina-2.webp",
    img2: "./img/masajistas/cami/cami-punto-masajes-argentina.webp",
    img3: "",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 71,
    nombre: "ANALIA",
    zona: "TRIBUNALES",
    horario: "Full time",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista",
    descripcion:
      "Soy Analia Masajistas Auxiliar de Kinesiologia Profesional y Matriculada,  masajes terapéuticos sobre camilla en cuerpo entero con cremas, musculares y cervicales.",
    telefono: "11 3207-4490",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541132074490&text=Hola%20ANALIA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/analia/analia-punto-masajes-argentina.webp",
    img2: "",
    img3: "",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 72,
    nombre: "DENU",
    zona: "TRIBUNALES",
    horario: "Lunes a sábados 11 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masaje tailandes",
    descripcion:
      "Masajes tradicionales. Son técnicas combinadas Shiatsu tailandés, reflexología, masajes deportivos.",
    telefono: "11 5573-1906",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541155731906&text=Hola%20DELY%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/dely/dely-punto-masajes-argentina.webp",
    img2: "",
    img3: "",
    img4: "",
    destacada: true,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 73,
    nombre: "ASTRID",
    zona: "PALERMO",
    horario: "Lunes a sábados 10 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes sensitivos",
    descripcion:
      "Masajes con técnicas combinadas. Trabajando todo el cuerpo desde los pies a la cabeza. Con shiatsu, tailandés, deportivo, reflexologia en manos y pies y dígito puntura.",
    telefono: "11 5837-6914",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541158376914&text=Hola%20ASTRID%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/astrid/astrid-punto-masajes-argentina-4.webp",
    img2: "./img/masajistas/astrid/astrid-punto-masajes-argentina-2.webp",
    img3: "./img/masajistas/astrid/astrid-punto-masajes-argentina-3.webp",
    img4: "./img/masajistas/astrid/astrid-punto-masajes-argentina.webp",
    destacada: true,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 74,
    nombre: "RUBY",
    zona: "RECOLETA",
    horario: "Lunes a sábados 12 a 21",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes sensitivos",
    descripcion:
      "El servicio consiste en masajes relajantes, deportivos y sensitivos, también realizo masajes naturista. Trabajo sobre camilla o tatami. Contas con servicio de ducha y bebida sin cargo.",
    telefono: "11 6462-9750",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541164629750&text=Hola%20RUBY%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/ruby/ruby-punto-masajes-argentina-2.webp",
    img2: "./img/masajistas/ruby/ruby-punto-masajes-argentina-3.webp",
    img3: "./img/masajistas/ruby/ruby-punto-masajes-argentina-4.webp",
    img4: "./img/masajistas/ruby/ruby-punto-masajes-argentina.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 75,
    nombre: "MAITE",
    zona: "RECOLETA",
    horario: "A convenir",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista terapéutica",
    descripcion:
      "Te ofrezco una sesión de masajes con distintas técnicas, tailandés, californiano, descontracturantes, relajantes , sensitivos, energizantes , desde los pies hasta la zona cervical.",
    telefono: "11 6364-2482",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541163642482&text=Hola%20MAITE%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/maite/maite-punto-masajes-argentina-3.webp",
    img2: "./img/masajistas/maite/maite-punto-masajes-argentina-2.webp",
    img3: "./img/masajistas/maite/maite-punto-masajes-argentina-maite.webp",
    img4: "./img/masajistas/maite/maite-punto-masajes-argentina.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 76,
    nombre: "ALDY",
    zona: "TRIBUNALES",
    horario: "Lunes a viernes 13 a 19",
    pago: "Solo Efectivo",
    titular: "Masajes 100% reales",
    descripcion:
      "Masajista profesional, deportivos, descontracturantes, relajantes, sensitivos-sedativos, anti-estres, reflexologia mano, pies y rostro, piedras calientes, californianos.",
    telefono: "11 6043-8640",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541160438640&text=Hola%20ALDY%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/aldy/aldy-punto-masajes-argentina.webp",
    img2: "./img/masajistas/aldy/aldy-punto-masajes-argentina-2.webp",
    img3: "./img/masajistas/aldy/aldy-punto-masajes-argentina-3.webp",
    img4: "./img/masajistas/aldy/aldy-punto-masajes-argentina-4.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 77,
    nombre: "AMALIA",
    zona: "MARTINEZ",
    horario: "Lunes a viernes 10 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes descontracturantes, relajantes, de los pies hasta a la cervical, servicio de ducha, ambiente climatizado.",
    telefono: "11 2785-0570",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541127850570&text=Hola%20AMALIA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/amalia/amalia-punto-masajes-argentina-2.webp",
    img2: "./img/masajistas/amalia/amalia-punto-masajes-argentina.webp",
    img3: "./img/masajistas/amalia/amalia-punto-masajes-argentina-3.webp",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 78,
    nombre: "ALMA",
    zona: "ALMAGRO",
    horario: "Lunes a sábados 9 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes profesionales",
    descripcion: "Servicio de masajes profesional.",
    telefono: "11 3662-0193",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541136620193&text=Hola%20ALMA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/alma/alma-punto-masajes-argentina-3.webp",
    img2: "./img/masajistas/alma/alma-punto-masajes-argentina.webp",
    img3: "./img/masajistas/alma/alma-punto-masajes-argentina-2.webp",
    img4: "./img/masajistas/alma/alma-punto-masajes-argentina-4.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 79,
    nombre: "PILAR",
    zona: "PALERMO",
    horario: "Lunes a viernes 13 a 18",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista profesional",
    descripcion:
      "Masajes relajantes, descontracturantes en tatami o camilla. La terapia que prefieras...",
    telefono: "11 3622-8530",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541136228530&text=Hola%20PILAR%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/pilar/pilar-punto-masajes-argentina-3.webp",
    img2: "./img/masajistas/pilar/pilar-punto-masajes-argentina.webp",
    img3: "./img/masajistas/pilar/pilar-punto-masajes-argentina-2.webp",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 80,
    nombre: "SOL",
    zona: "COLEGIALES",
    horario: "Lunes a sábados 9 a 17",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes terapéuticos",
    descripcion:
      "Los masajes son relajantes ayurbeda deportiva sedativo. Trabajamos de pies a cabeza con movimientos circulares muy relajantes o el tipo de masajes te guste.",
    telefono: "11 6119-6047",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541161196047&text=Hola%20SOL%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/sol-2/sol-punto-masajes-argentina-5.webp",
    img2: "./img/masajistas/sol-2/sol-punto-masajes-argentina-6.webp",
    img3: "./img/masajistas/sol-2/sol-punto-masajes-argentina-7.webp",
    img4: "./img/masajistas/sol-2/sol-punto-masajes-argentina-8.webp",
    destacada: true,
    posicion: "",
    tag: "pago",
    activado: true,
  },
  {
    id: 81,
    nombre: "MARIA",
    zona: "CONGRESO",
    horario: "Lunes a sábados",
    pago: "Solo Efectivo",
    titular: "Masajes",
    descripcion:
      "Te ofrezco en un lugar calido y tranquilo. Los masajes que buscas. Relajantes descontracturantes, sensitivos, circulatorios.",
    telefono: "11 2370-3619",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541123703619&text=Hola%20MARIA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/maria-4/maria-punto-masajes-argentina.webp",
    img2: "./img/masajistas/maria-4/maria-punto-masajes-argentina-2.webp",
    img3: "",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 82,
    nombre: "MARU",
    zona: "CONGRESO",
    horario: "Lunes a sábados 11 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista profesional",
    descripcion: "Masajes descontracturante y relajante deportivos sedativos.",
    telefono: "11 6879-4192",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541168794192&text=Hola%20MARU%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/maru/maru-punto-masajes-argentina-2.webp",
    img2: "./img/masajistas/maru/maru-punto-masajes-argentina.webp",
    img3: "./img/masajistas/maru/maru-punto-masajes-argentina-3.webp",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 83,
    nombre: "DENISSE",
    zona: "CONGRESO",
    horario: "Lunes a sábados 10 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes terapéuticos",
    descripcion:
      "Excelentes masajes descontracturantes, relajantes, reflexología, atención personalizada con la mejor onda y simpatía. Lugar confortable.",
    telefono: "11 3374-9281",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541133749281&text=Hola%20DENISSE%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/carla/carla-punto-masajes-argentina.webp",
    img2: "./img/masajistas/carla/carla-punto-masajes-argentina-2.webp",
    img3: "./img/masajistas/carla/carla-punto-masajes-argentina-3.webp",
    img4: "./img/masajistas/carla/carla-punto-masajes-argentina-4.webp",
    destacada: true,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 84,
    nombre: "RITA",
    zona: "TRIBUNALES",
    horario: "Lunes a domingos 10 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes terapéuticos",
    descripcion:
      "Masaje descontracturante, deportivo, sedativo, sensitivo, drenaje linfático.",
    telefono: "11 3650-6450",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541136506450&text=Hola%20RITA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/rita/rita-punto-masajes-argentina.webp",
    img2: "./img/masajistas/rita/rita-punto-masajes-argentina-2.webp",
    img3: "",
    img4: "",
    destacada: true,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 85,
    nombre: "LUNA",
    zona: "CABALLITO",
    horario: "Lunes a domingos 11 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes descontracturantes",
    descripcion:
      "Brindo servicio profesional de masajes, sobre camilla o tatami japonés, servicio de ducha y música funcional.",
    telefono: "11 2625-1484",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541126251484&text=Hola%20LUNA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/luna/luna-punto-masajes-argentina.webp",
    img2: "./img/masajistas/luna/luna-punto-masajes-argentina-2.webp",
    img3: "./img/masajistas/luna/luna-punto-masajes-argentina-3.webp",
    img4: "",
    destacada: true,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 86,
    nombre: "JACKELINE",
    zona: "CABALLITO",
    horario: "Lunes a domingos 12 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista profesional",
    descripcion:
      "Masajes sensitivos descontracturante  sobre camilla o tatami japonés. Ambiente climatizado y música funcional con servicio de baño.",
    telefono: "11 5383-7609",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541153837609&text=Hola%20JACKELINE%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/jackeline/jackeline-punto-masajes-argentina.webp",
    img2: "./img/masajistas/jackeline/jackeline-punto-masajes-argentina-2.webp",
    img3: "",
    img4: "",
    destacada: true,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 87,
    nombre: "GIMENA",
    zona: "MICROCENTRO",
    horario: "Lunes a sábados 10 a 18",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista profesional",
    descripcion:
      "Masajes descontracturantes, Relajantes, deportivos. Buena atención. Ambiente climatizado. Servicio de duchas.",
    telefono: "11 5755-2570",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541157552570&text=Hola%20GIMENA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/gimena/gimena-punto-masajes-argentina.webp",
    img2: "./img/masajistas/gimena/gimena-punto-masajes-argentina-2.webp",
    img3: "./img/masajistas/gimena/gimena-punto-masajes-argentina-3.webp",
    img4: "./img/masajistas/gimena/gimena-punto-masajes-argentina-4.webp",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 88,
    nombre: "MIA",
    zona: "PALERMO",
    horario: "Lunes a domingos 14 a 21",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes sensitivos en mi gabinete en la mejor zona de Palermo te espero para que sientas el verdadero placer de un excepcional masaje descontracturante, circulatorio, relajante…",
    telefono: "11 3386-9889",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541133869889&text=Hola%20MIA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/mia/mia-punto-masajes-argentina.webp",
    img2: "./img/masajistas/mia/mia-punto-masajes-argentina-2.webp",
    img3: "",
    img4: "",
    destacada: true,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 90,
    nombre: "BRIGITTE",
    zona: "PALERMO",
    horario: "Lunes a domingos 14 a 21",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes sensitivos en mi gabinete en la mejor zona de Palermo te espero para que sientas el verdadero placer de un excepcional masaje descontracturante, circulatorio, relajante…",
    telefono: "11 3386-9889",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541133869889&text=Hola%20BRIGITTE%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/brigitte/brigitte-punto-masajes-argentina.webp",
    img2: "./img/masajistas/brigitte/brigitte-punto-masajes-argentina-2.webp",
    img3: "./img/masajistas/brigitte/brigitte-punto-masajes-argentina-3.webp",
    img4: "",
    destacada: true,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 91,
    nombre: "ARACELI",
    zona: "VILLA DEVOTO",
    horario: "Lunes a domingos 10 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masoterapeuta",
    descripcion:
      "Soy masoterapeuta y aux.de kinesiología. Realizó masajes relajantes, descontracturante, deportivo, kinesiología, facial, Reflexiólogia y bambuterapia.",
    telefono: "11 6605-3696",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541166053696&text=Hola%20ARACELI%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/araceli/araceli-punto-masajes-argentina.webp",
    img2: "./img/masajistas/araceli/araceli-punto-masajes-argentina-2.webp",
    img3: "",
    img4: "",
    destacada: true,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 92,
    nombre: "YOANA",
    zona: "ALMAGRO",
    horario: "Lunes a sábados 10 a 20",
    pago: "Solo Efectivo",
    titular: "Masajista terapéutica",
    descripcion: "Masaje descontraurantes sensitivos.",
    telefono: "11 6886-8420",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541168868420&text=Hola%20YOANA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/yoana/yoana-punto-masajes-argentina.webp",
    img2: "",
    img3: "",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 93,
    nombre: "LILI",
    zona: "CONGRESO",
    horario: "Full time",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes sensitivos",
    descripcion:
      "Me manejo en hoteles y domicilio zona Congreso. También hoteles de turistas. Masajes profesionales, deportivos, terapéutico...",
    telefono: "11 2179-1192",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541121791192&text=Hola%20LILI%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/lili/lili-punto-masajes-argentina.webp",
    img2: "./img/masajistas/lili/lili-punto-masajes-argentina.webp-2",
    img3: "./img/masajistas/lili/lili-punto-masajes-argentina.webp-3",
    img4: "./img/masajistas/lili/lili-punto-masajes-argentina.webp-4",
    destacada: true,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 94,
    nombre: "MEGAN",
    zona: "RECOLETA",
    horario: "Lunes a sábados 10 a 24",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes sensitivos",
    descripcion:
      "Realizo masajes descontracturantes relajantes sensitivos, gabinete con ducha disponible en recoleta.",
    telefono: "11 5989-3943",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541159893943&text=Hola%20MEGAN%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/megan/megan-punto-masajes-argentina.webp",
    img2: "./img/masajistas/megan/megan-punto-masajes-argentina-2.webp",
    img3: "./img/masajistas/megan/megan-punto-masajes-argentina-3.webp",
    img4: "",
    destacada: true,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 95,
    nombre: "ABRIL",
    zona: "MICROCENTRO",
    horario: "Lunes a viernes 12 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista profesional",
    descripcion: "Servicio a hombres, Mujeres, Parejas, Domicilios y Hoteles.",
    telefono: "11 2649-0368",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541126490368&text=Hola%20ABRIL%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/abril-2/abril-punto-masajes-argentina.webp",
    img2: "",
    img3: "",
    img4: "",
    destacada: true,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 96,
    nombre: "ANDREA",
    zona: "FLORES",
    horario: "Lunes a sábados 10 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes de excelencia",
    descripcion:
      "Masajes relajantes, descontracturantes, deportivo, desbloqueo cervical y lumbar. Técnicas orientales: Tai Massage, ayurveda. Servicio de ducha disponible.",
    telefono: "11 4069-5171",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541140695171&text=Hola%20ANDREA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/andrea/andrea-punto-masajes-argentina-5.webp",
    img2: "./img/masajistas/andrea/andrea-punto-masajes-argentina.webp",
    img3: "./img/masajistas/andrea/andrea-punto-masajes-argentina-2.webp",
    img4: "./img/masajistas/andrea/andrea-punto-masajes-argentina-3.webp",
    destacada: true,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 97,
    nombre: "SOLEDAD",
    zona: "RECOLETA",
    horario: "Lunes a sábados 10 a 18",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes profesionales",
    descripcion:
      "Ofrezco servicio de masajes profesionales y descontracturantes en mi gabinete ubicado en recoleta.",
    telefono: "11 5862-3364",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541158623364&text=Hola%20SOLEDAD%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/soledad-2/soledad-punto-masajes-argentina.webp",
    img2: "./img/masajistas/soledad-2/soledad-punto-masajes-argentina-2.webp",
    img3: "",
    img4: "",
    destacada: false,
    posicion: "",
    tag: "",
    activado: false,
  },
  {
    id: 98,
    nombre: "EMILY",
    zona: "TIGRE",
    horario: "Lunes a sábados 9 a 21",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes de excelencia",
    descripcion:
      "Masajista Profesional Matriculada y Terapeuta Thai. Masajes relajantes, descontracturantes, deportivo, desbloqueo cervical y lumbar. Técnicas orientales: Tai Massage, ayurveda.",
    telefono: "11 5046-9837",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541150469837&text=Hola%20EMILY%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/emily/emily-punto-masajes-argentina.webp",
    img2: "./img/masajistas/emily/emily-punto-masajes-argentina-2.webp",
    img3: "./img/masajistas/emily/emily-punto-masajes-argentina-3.webp",
    img4: "./img/masajistas/emily/emily-punto-masajes-argentina-4.webp",
    destacada: true,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 99,
    nombre: "PAMELA",
    zona: "VILLA LURO",
    horario: "Lunes a viernes 12 a 21",
    pago: "Efectivo y Mercadopago",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes relajantes, descontracturantes, deportivo, desbloqueo cervical y lumbar,  sensoriales y californianos. Técnicas orientales: Tai Massage, ayurveda.",
    telefono: "11 4069-5171",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541140695171&text=Hola%20PAMELA%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/pamela/pamela-punto-masajes-argentina.webp",
    img2: "./img/masajistas/pamela/pamela-punto-masajes-argentina-2.webp",
    img3: "./img/masajistas/pamela/pamela-punto-masajes-argentina-3.webp",
    img4: "./img/masajistas/pamela/pamela-punto-masajes-argentina-4.webp",
    destacada: true,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 100,
    nombre: "MARIEL",
    zona: "MICROCENTRO",
    horario: "Lunes a viernes 12 a 19",
    pago: "Solo Efectivo",
    titular: "Masajes relajantes",
    descripcion:
      "Masajes relajantes, sensitivos, descontracturantes. Solicita tu turno.",
    telefono: "11 5010-5222",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541150105222&text=Hola%20MARIEL%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/mariel-2/mariel-punto-masajes-argentina.webp",
    img2: "./img/masajistas/mariel-2/mariel-punto-masajes-argentina-2.webp",
    img3: "",
    img4: "",
    destacada: true,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 101,
    nombre: "VICKY",
    zona: "TRIBUNALES",
    horario: "Lunes a viernes 14 a 20",
    pago: "Efectivo y Mercadopago",
    titular: "Fisio y masoterapeuta profesional",
    descripcion:
      "Realizo masajes profesionales, descontracturantes, relajantes y sensitivos en mi gabinete totalmente equipado, confortable e impecable.",
    telefono: "11 2319-7014",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541123197014&text=Hola%20VICKY%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/vicky/vicky-punto-masajes-argentina.webp",
    img2: "./img/masajistas/vicky/vicky-punto-masajes-argentina-2.webp",
    img3: "./img/masajistas/vicky/vicky-punto-masajes-argentina-3.webp",
    img4: "./img/masajistas/vicky/vicky-punto-masajes-argentina-4.webp",
    destacada: true,
    posicion: "",
    tag: "",
    activado: true,
  },
  {
    id: 102,
    nombre: "AILEN",
    zona: "CONGRESO",
    horario: "Lunes a viernes 11 a 19",
    pago: "Efectivo y Mercadopago",
    titular: "Masajista profesional",
    descripcion:
      "Masajes relajantes, descontracturantes, deportivos desde los pies hasta la cervical.",
    telefono: "11 6430-2280",
    btWhatsapp:
      "https://api.whatsapp.com/send?phone=541164302280&text=Hola%20AILEN%20te%20vi%20en%20Punto%20Masajes.%20Quiero%20saber%20m%C3%A1s%20de%20tu%20servicio.",
    img: "./img/masajistas/ailen/ailen-punto-masajes-argentina.webp",
    img2: "./img/masajistas/ailen/ailen-punto-masajes-argentina-2.webp",
    img3: "./img/masajistas/ailen/ailen-punto-masajes-argentina-3.webp",
    img4: "./img/masajistas/ailen/ailen-punto-masajes-argentina-4.webp",
    destacada: true,
    posicion: "",
    tag: "pago",
    activado: true,
  },
];

///////////////////////////////////////////////////////////////////////////////

let destacadas = document.getElementById("masDestacadas");

productos.forEach((ele) => {
  if (ele.destacada === true && ele.activado === true) {
    let card = document.createElement("div");
    card.innerHTML = `
        <div class="contenedor" id=${ele.id}>
            <div class="gridImgDestacada">
                <div>
                    <img src=${ele.img} alt="${ele.nombre} ${ele.titular} masajista en ${ele.zona}">
                </div>
            </div>
            <div class="gridInfoDestacada">
                <h3>${ele.nombre} <span class="txtGreen">${ele.zona}</span></h3>
                    <div class="masContacto">
                        <p>Teléfono: ${ele.telefono}</p>
                        <p>${ele.horario}</p>
                    </div>
                    <h4><span class="txtGreen">${ele.titular}</span></h4>
                    <p class="descripcion">${ele.descripcion}<p>
            </div>
            <div class="gridWA">
                <a target="_blank" href="${ele.btWhatsapp}" rel="nofollow">
                    <button class="btnWA"><img src="./img/whatsappx16.png" alt="Boton-de-WhatsApp">Whatsapp</button>
                </a>
                <div>         
                    <button class="btnPhotos" onclick = btnPhotos(${ele.id})>Ver fotos</button>    
                </div>
            </div>
        </div>`;
    destacadas.appendChild(card);
  }
});

function btnPhotos(id) {
  let prodFind = productos.find((el) => el.id === id);
  let card = document.createElement("div");
  card.innerHTML = `
    <div class="window-notice" id="window-notice">
        <div class="content">
            <div class="content-text">
                <img src=${prodFind.img}>
                <img src=${prodFind.img2}>
                <img src=${prodFind.img3}>
                <img src=${prodFind.img4}>
            </div>
            <div class="content-buttons">
                <button id="close-button" onclick=removeBtn()>
                  CERRAR
                </button>
            </div>
        </div>
    </div>
    `;
  destacadas.appendChild(card);
}
function removeBtn() {
  let ventana = document.getElementById("window-notice");
  ventana.remove();
}

let gratis = document.getElementById("masGeneral");

let ordenar = productos.sort(() => (Math.random() > 0.5 ? 1 : -1));
productos.forEach((el) => {
  if (el.destacada === false && el.activado === true) {
    let card = document.createElement("div");
    card.innerHTML = `
    <div class="contenedorFree">
      <div class="gridInfoDestacadaFree">
        <h3>${el.nombre} <span class="txtGreen">${el.zona}</span></h3>
        <div class="masContacto">
          <p>Teléfono: ${el.telefono}</p>
          <p>${el.horario}</p>
        </div>
        <h4><span class="txtGreen">${el.titular}</span></h4>
        <p class="descripcion">${el.descripcion}<p>
      </div>
      <div class="gridWA">
        <a target="_blank" href="${el.btWhatsapp}" rel="nofollow">
          <button class="btnWA"><img src="./img/whatsappx16.png" alt="Boton de WhatsApp">Whatsapp</button>
        </a>
        <div>
          <button class="btnPhotos" onclick = btnPhotos(${el.id})>Ver fotos</button>
        </div>

      </div>
    </div>`;
    gratis.appendChild(card);
  }
});
